-- MySQL Script generated by MySQL Workbench
-- Tue May 21 19:33:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ejercicios-U3-FundBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ejercicios-U3-FundBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ejercicios-U3-FundBD` DEFAULT CHARACTER SET utf8 ;
USE `Ejercicios-U3-FundBD` ;

-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`Profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `ApellidoMat` VARCHAR(20) NOT NULL,
  `ApellidoPat` VARCHAR(20) NOT NULL,
  `CP` VARCHAR(5) NOT NULL,
  `Calle` VARCHAR(50) NOT NULL,
  `NumeroInterior` VARCHAR(5) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`Modulo` (
  `idModulo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `DNI_Profesor` INT NOT NULL,
  `Modulocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModulo`),
  UNIQUE INDEX `DNI_Profesor_UNIQUE` (`DNI_Profesor` ASC) VISIBLE,
  CONSTRAINT `DNI_Profesor`
    FOREIGN KEY (`DNI_Profesor`)
    REFERENCES `Ejercicios-U3-FundBD`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`Alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoMat` VARCHAR(45) NOT NULL,
  `ApellidoPat` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `DelegadoAlumno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCurso`),
  CONSTRAINT `DelegadoAlumno`
    FOREIGN KEY ()
    REFERENCES `Ejercicios-U3-FundBD`.`Alumno` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`AlumnoCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`AlumnoCurso` (
  `idAlumno` INT NOT NULL,
  `idCurso` INT NOT NULL,
  UNIQUE INDEX `idAlumno_UNIQUE` (`idAlumno` ASC) VISIBLE,
  UNIQUE INDEX `idCurso_UNIQUE` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `Ejercicios-U3-FundBD`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAlumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `Ejercicios-U3-FundBD`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`AlumnoModulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`AlumnoModulo` (
  `idAlumno` INT NOT NULL,
  `idModulo` INT NOT NULL,
  INDEX `idAlumno_idx` (`idAlumno` ASC) VISIBLE,
  INDEX `idModulo_idx` (`idModulo` ASC) VISIBLE,
  CONSTRAINT `idAlumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `Ejercicios-U3-FundBD`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idModulo`
    FOREIGN KEY (`idModulo`)
    REFERENCES `Ejercicios-U3-FundBD`.`Modulo` (`idModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`Coche`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`Coche` (
  `Matricula` INT NOT NULL AUTO_INCREMENT,
  `Modelo` INT NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`Cliente` (
  `DNI` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoMat` VARCHAR(45) NOT NULL,
  `ApellidoPat` VARCHAR(45) NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `NumInt` INT(5) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`CocheNuevo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`CocheNuevo` (
  `MatriculaCoche` INT NOT NULL,
  `Unidades` INT NOT NULL,
  UNIQUE INDEX `MatriculaCoche_UNIQUE` (`MatriculaCoche` ASC),
  CONSTRAINT `MatriculaCoche`
    FOREIGN KEY (`MatriculaCoche`)
    REFERENCES `Ejercicios-U3-FundBD`.`Coche` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`CocheViejo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`CocheViejo` (
  `MatriculaCoche` INT NOT NULL,
  `Kilometros` INT NOT NULL,
  UNIQUE INDEX `MatriculaCoche_UNIQUE` (`MatriculaCoche` ASC),
  CONSTRAINT `MatriculaCoche`
    FOREIGN KEY (`MatriculaCoche`)
    REFERENCES `Ejercicios-U3-FundBD`.`Coche` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`FichaCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`FichaCompra` (
  `idFichaCompra` INT NOT NULL AUTO_INCREMENT,
  `MatriculaCoche` INT NOT NULL,
  `DNICliente` INT NOT NULL,
  PRIMARY KEY (`idFichaCompra`, `DNICliente`, `MatriculaCoche`),
  UNIQUE INDEX `MatriculaCoche_UNIQUE` (`MatriculaCoche` ASC) VISIBLE,
  UNIQUE INDEX `DNICliente_UNIQUE` (`DNICliente` ASC) VISIBLE,
  CONSTRAINT `MatriculaCocheFicha`
    FOREIGN KEY (`MatriculaCoche`)
    REFERENCES `Ejercicios-U3-FundBD`.`Coche` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNIClienteFicha`
    FOREIGN KEY (`DNICliente`)
    REFERENCES `Ejercicios-U3-FundBD`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`Mecanico` (
  `DNI` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoMat` VARCHAR(45) NOT NULL,
  `ApellidoPat` VARCHAR(45) NOT NULL,
  `FechaContratacion` DATE NOT NULL,
  `Salario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicios-U3-FundBD`.`Reparacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicios-U3-FundBD`.`Reparacion` (
  `DNIMecanico` INT NOT NULL,
  `MatriculaCoche` INT NOT NULL,
  `FechaReparacion` DATE NOT NULL,
  `HorasInvertidas` INT NOT NULL,
  UNIQUE INDEX `DNIMecanico_UNIQUE` (`DNIMecanico` ASC) VISIBLE,
  UNIQUE INDEX `MatriculaCoche_UNIQUE` (`MatriculaCoche` ASC) VISIBLE,
  CONSTRAINT `DNIMecanico`
    FOREIGN KEY (`DNIMecanico`)
    REFERENCES `Ejercicios-U3-FundBD`.`Mecanico` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MatriculaCoche`
    FOREIGN KEY (`MatriculaCoche`)
    REFERENCES `Ejercicios-U3-FundBD`.`Coche` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
