-- MySQL Script generated by MySQL Workbench
-- Tue May 21 19:01:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ejercicio3-U3-FundBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ejercicio3-U3-FundBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ejercicio3-U3-FundBD` DEFAULT CHARACTER SET utf8 ;
USE `Ejercicio3-U3-FundBD` ;

-- -----------------------------------------------------
-- Table `Ejercicio3-U3-FundBD`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio3-U3-FundBD`.`Profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) NOT NULL,
  `ApellidoMat` VARCHAR(20) NOT NULL,
  `ApellidoPat` VARCHAR(20) NOT NULL,
  `CP` VARCHAR(5) NOT NULL,
  `Calle` VARCHAR(50) NOT NULL,
  `NumeroInterior` VARCHAR(5) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio3-U3-FundBD`.`Modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio3-U3-FundBD`.`Modulo` (
  `idModulo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `DNI_Profesor` INT NOT NULL,
  `Modulocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModulo`),
  UNIQUE INDEX `DNI_Profesor_UNIQUE` (`DNI_Profesor` ASC) VISIBLE,
  CONSTRAINT `DNI_Profesor`
    FOREIGN KEY (`DNI_Profesor`)
    REFERENCES `Ejercicio3-U3-FundBD`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio3-U3-FundBD`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio3-U3-FundBD`.`Alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoMat` VARCHAR(45) NOT NULL,
  `ApellidoPat` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio3-U3-FundBD`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio3-U3-FundBD`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `DelegadoAlumno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCurso`),
  CONSTRAINT `DelegadoAlumno`
    FOREIGN KEY ()
    REFERENCES `Ejercicio3-U3-FundBD`.`Alumno` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio3-U3-FundBD`.`AlumnoCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio3-U3-FundBD`.`AlumnoCurso` (
  `idAlumno` INT NOT NULL,
  `idCurso` INT NOT NULL,
  UNIQUE INDEX `idAlumno_UNIQUE` (`idAlumno` ASC) VISIBLE,
  UNIQUE INDEX `idCurso_UNIQUE` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `Ejercicio3-U3-FundBD`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAlumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `Ejercicio3-U3-FundBD`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ejercicio3-U3-FundBD`.`AlumnoModulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ejercicio3-U3-FundBD`.`AlumnoModulo` (
  `idAlumno` INT NOT NULL,
  `idModulo` INT NOT NULL,
  INDEX `idAlumno_idx` (`idAlumno` ASC) VISIBLE,
  INDEX `idModulo_idx` (`idModulo` ASC) VISIBLE,
  CONSTRAINT `idAlumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `Ejercicio3-U3-FundBD`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idModulo`
    FOREIGN KEY (`idModulo`)
    REFERENCES `Ejercicio3-U3-FundBD`.`Modulo` (`idModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
